Fix TS error in tools/package-release (#59569)
The error was causing pnpm --filter='./tools/package-release' build to fail
with

src/validate.ts:118:86 - error TS2345: Argument of type 'string' is not assignable to parameter of type 'never'.

118   .filter( ( name: string ) => excludedPackages.length && excludedPackages.includes( name ) );