Update telemetry tracking in the email editor (#58294)
* Restore tracking of editor_layout_loaded event

WOOPLUG-3953

* Add a mechanism for tracking actions on stores and track setDeviceType

WOOPLUG-3953

* Restore header_preview_dropdown_send_test_email_selected event

WOOPLUG-3953

* Add a simple mechanism for tracking clicks and track open preview

WOOPLUG-3953

* Restor tracking of moving post to trash

WOOPLUG-3953

* Improve naming and add commentes to store actions tracking code

WOOPLUG-3953

* Restore tracking of inserter and listview sidebars

WOOPLUG-3953

* Restore tracking of header_blocks_tool_button_clicked

WOOPLUG-3953

* Restore tracking of header_more_menu_dropdown_toggle

WOOPLUG-3953

* Add tracking of feature toggled in more menu

WOOPLUG-3953

* Restore trackig of header_save_all_button_clicked event

WOOPLUG-3953

* Restore tracking of header_save_email_button_clicked

WOOPLUG-3953

* Restore tracking of closing inserter sidebar

WOOPLUG-3953

* Add tracking of inserting blocks and patterns

WOOPLUG-3953

* Restore tracking of header_preview_dropdown_clicked

WOOPLUG-3953

* Reintroduce Email,Block tabs tracking in the sidebar

WOOPLUG-3953

* Refactor list view, open, close tracking, and inserter open tracking

This commit unifies this event with the rest of the events that track
isOpened within the event data instead of tracking separate events
for open and close.

It also moves the tracking to the DOM to track only interactions
via the buttons in the header. The panels are sometimes programmatically closed
for example, when a user selects distraction-free mode.

WOOPLUG-3953

* Add e2e test to verify selectors used for tracking are present

WOOPLUG-3953

* Fix email editor page render PHP error in PHP 7.4

PHP 7.4 doesn't support array spread.
error: Uncaught Error: Cannot unpack array with string keys
WOOPLUG-3953

* Update name of save email button event

It is no longes save all button but just save button
WOOPLUG-3953

* Add documentation page for telemetry tracking

WOOPLUG-3953

* Add tracking for command menu

WOOPLUG-3953

* Add changelog

WOOPLUG-3953

* Fix the broken open preview to a new tab

This could potentialy cause multiple issues for cases where
code relied on the returned value of an action.
WOOPLUG-3953

* Add tracking of the show template toggle in the preview menu

WOOPLUG-3953

* Add tracking of email status change

Currently, the email editor is still not fully refactored to a module
that exports functions, so I followed the principle used for RichTextButton
and passed tracking functionality via a filter.

I consider this a temporary solution until we add exports to the email editor package.
WOOPLUG-3953

* Add tracking of recipients settings in the editor integration

WOOPLUG-3953

* Add tracking of Sender options in template mode's sidebar

WOOPLUG-3953